version: "3"

x-env: &env
  TZ: Asia/Tokyo
  NEXT_PUBLIC_ZOOM_SDK_KEY: ""
  NEXT_PUBLIC_ZOOM_SDK_SECRET: ""

services:
  typescript:
    build:
      context: .
      dockerfile: ./typescript/Dockerfile.dev
    environment:
      <<: *env
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ${HOME}/.gitconfig:/root/.gitconfig
      - .:/app
      - /typescript/node_modules
      - /typescript/.next

volumes:
  typescript:
    driver: local
